---

env:
  VERBOSE: true
  ANKA_MOJAVE_TEMPLATE: "10.14.4_6C_14G_40G"
  ANKA_TEMPLATE_TAG: "clean::cicd::git-ssh::nas::brew::buildkite-agent-3.11.2"
  CHECKSUMABLE: "scripts/eosio_build*"
  MAC_TAG: "eosio_1.9.0-developv5"
  # LINUX_WORKDIR: "/home/cicd"
  # MAC_WORKDIR: "/home/anka"

steps:

  # - label: ":darwin: Ensure Mojave Anka Template Dependency Tag/Layer Exists"
  #   command:
  #     - "git clone git@github.com:EOSIO/mac-anka-fleet.git"
  #     - "cd mac-anka-fleet && . ./ensure_tag.bash -u 12 -r 25G -a '-n'"
  #   agents:
  #     - "queue=mac-anka-templater-fleet"
  #   env:
  #     REPO: "${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO}"
  #     REPO_COMMIT: "${BUILDKITE_COMMIT}"
  #     CHECKSUMABLE: "${CHECKSUMABLE}"
  #     TEMPLATE: "${ANKA_MOJAVE_TEMPLATE}"
  #     TEMPLATE_TAG: "${ANKA_TEMPLATE_TAG}"
  #     TAG_COMMANDS: "git clone ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO} && cd eos && git checkout ${BUILDKITE_COMMIT} && git submodule update --init --recursive && ./scripts/eosio_build.bash -y -m && cd .. && rm -rf eos" # CLONED_REPO_DIR IS REQUIRED and is where the repo is always cloned into
  #     PROJECT_TAG: "${MAC_TAG}"
  #   timeout: 320

  # - trigger: "mac-anka-fleet"
  #   label: ":anka: Ensure Mojave Anka Template Tag Exists"
  #   branches: "*"
  #   async: false
  #   build:
  #     branch: "master"
  #     env:
  #       REPO: "${BUILDKITE_REPO}"
  #       REPO_COMMIT: "${BUILDKITE_COMMIT}"
  #       CHECKSUMABLE: "${CHECKSUMABLE}"
  #       TEMPLATE: "${ANKA_MOJAVE_TEMPLATE}"
  #       TEMPLATE_TAG: "${ANKA_TEMPLATE_TAG}"
  #       TAG_COMMANDS: "CLONED_REPO_DIR/scripts/eosio_build.bash -y -m" # CLONED_REPO_DIR IS REQUIRED and is where the repo is always cloned into
  #       PROJECT_TAG: "${MAC_TAG}"

  # - wait

  ############################
  # BUILDING #################
  ############################

  - label: ":darwin: [Darwin] Mojave Build"
    command:
      - "git clone ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO} && cd eos && git checkout ${BUILDKITE_COMMIT} && git submodule update --init --recursive && ./scripts/eosio_build.bash -y -m && tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    plugins:
      chef/anka#v0.5.0:
        no-volume: true
        inherit-environment-vars: true
        vm-name: $ANKA_MOJAVE_TEMPLATE
        vm-registry-tag: "${ANKA_TEMPLATE_TAG}::${MAC_TAG}"
        modify-cpu: 12
        modify-ram: 24
        always-pull: true
        debug: true
        anka-debug: true
        wait-network: true
    agents:
      - "queue=mac-anka-large-node-fleet"
    timeout: 120
    retry:
      automatic:
        - exit_status: -1
          limit: 2

  - label: ":aws: Amazon Linux 2 Build"
    command:
      - "git clone ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO} && cd eos && git checkout ${BUILDKITE_COMMIT} && git submodule update --init --recursive && ./scripts/eosio_build.bash -y -P -m"
      - "tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:amazonlinux2_1-9-0-develop"
        mount-checkout: false
    timeout: 120

  - label: ":centos: CentOS 7 Build"
    command:
      - "git clone ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO} && cd eos && git checkout ${BUILDKITE_COMMIT} && git submodule update --init --recursive && ./scripts/eosio_build.bash -y -P -m"
      - "tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:centos7_1-9-0-develop"
        mount-checkout: false
    timeout: 120

  - label: ":ubuntu: Ubuntu 16.04 Build"
    command:
      - "git clone ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO} && cd eos && git checkout ${BUILDKITE_COMMIT} && git submodule update --init --recursive && ./scripts/eosio_build.bash -y -P -m"
      - "tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu16_1-9-0-develop"
        mount-checkout: false
    timeout: 120

  - label: ":ubuntu: Ubuntu 18.04 Build"
    command:
      - "git clone ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO} && cd eos && git checkout ${BUILDKITE_COMMIT} && git submodule update --init --recursive && ./scripts/eosio_build.bash -y -P -m"
      - "tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu18_1-9-0-develop"
        mount-checkout: false
    timeout: 120

  - wait

  # ################################
  # # TESTS ########################
  # ################################

  # MOJAVE #
  - label: ":darwin: [Darwin] Mojave Tests"
    command:
      - "git clone ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO} && cd eos && git checkout ${BUILDKITE_COMMIT} && buildkite-agent artifact download \"build.tar.gz\" . --step \":darwin: [Darwin] Mojave Build\""
      - "cd eos && ./scripts/parallel-test.bash"
    agents:
      - "queue=mac-anka-node-fleet"
    plugins:
      chef/anka#v0.5.0:
        no-volume: true
        inherit-environment-vars: true
        bash-interactive: true
        vm-name: $ANKA_MOJAVE_TEMPLATE
        vm-registry-tag: "${ANKA_TEMPLATE_TAG}::${MAC_TAG}"
        always-pull: true
        anka-debug: true
        debug: true
        wait-network: true
    timeout: 120
    retry:
      automatic:
        - exit_status: -1
          limit: 2

  - label: ":darwin: [Darwin] Mojave NP Tests"
    command:
      - "git clone ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO} && cd eos && git checkout ${BUILDKITE_COMMIT} && buildkite-agent artifact download \"build.tar.gz\" . --step \":darwin: [Darwin] Mojave Build\""
      - "cd eos && ./scripts/serial-test.bash"
    agents:
      - "queue=mac-anka-node-fleet"
    plugins:
      chef/anka#v0.5.0:
        no-volume: true
        inherit-environment-vars: true
        bash-interactive: true
        vm-name: $ANKA_MOJAVE_TEMPLATE
        vm-registry-tag: "${ANKA_TEMPLATE_TAG}::${MAC_TAG}"
        always-pull: true
        anka-debug: true
        debug: true
        wait-network: true
    timeout: 120
    retry:
      automatic:
        - exit_status: -1
          limit: 2
          
  # AmazonLinux #
  - label: ":aws: Amazon Linux 2 Tests"
    command:
      - "git clone ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO} && cd eos && git checkout ${BUILDKITE_COMMIT} && buildkite-agent artifact download \"build.tar.gz\" . --step \":aws: Amazon Linux 2 Build\""
      - "./scripts/parallel-test.bash"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:amazonlinux2_1-9-0-develop"
        mount-checkout: false
    timeout: 60

  - label: ":aws: Amazon Linux 2 NP Tests"
    command:
      - "git clone ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO} && cd eos && git checkout ${BUILDKITE_COMMIT} && buildkite-agent artifact download \"build.tar.gz\" . --step \":aws: Amazon Linux 2 Build\""
      - "./scripts/serial-test.bash"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:amazonlinux2_1-9-0-develop"
        mount-checkout: false
    timeout: 60

  # CentOS #
  - label: ":centos: CentOS 7 Tests"
    command:
      - "git clone ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO} && cd eos && git checkout ${BUILDKITE_COMMIT} && buildkite-agent artifact download \"build.tar.gz\" . --step \":centos: CentOS 7 Build\""
      - "./scripts/parallel-test.bash"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:centos7_1-9-0-develop"
        mount-checkout: false
    timeout: 60

  - label: ":centos: CentOS 7 NP Tests"
    command:
      - "git clone ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO} && cd eos && git checkout ${BUILDKITE_COMMIT} && buildkite-agent artifact download \"build.tar.gz\" . --step \":centos: CentOS 7 Build\""
      - "source /opt/rh/rh-python36/enable && ./scripts/serial-test.bash"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:centos7_1-9-0-develop"
        mount-checkout: false
    timeout: 60

  # Ubuntu #
  - label: ":ubuntu: Ubuntu 16.04 Tests"
    command:
      - "git clone ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO} && cd eos && git checkout ${BUILDKITE_COMMIT} && buildkite-agent artifact download \"build.tar.gz\" . --step \":ubuntu: Ubuntu 16.04 Build\""
      - "./scripts/parallel-test.bash"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu16_1-9-0-develop"
        mount-checkout: false
    timeout: 60

  - label: ":ubuntu: Ubuntu 16.04 NP Tests"
    command:
      - "git clone ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO} && cd eos && git checkout ${BUILDKITE_COMMIT} && buildkite-agent artifact download \"build.tar.gz\" . --step \":ubuntu: Ubuntu 16.04 Build\""
      - "./scripts/serial-test.bash"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu16_1-9-0-develop"
        mount-checkout: false
    timeout: 60

  - label: ":ubuntu: Ubuntu 18.04 Tests"
    command:
      - "git clone ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO} && cd eos && git checkout ${BUILDKITE_COMMIT} && buildkite-agent artifact download \"build.tar.gz\" . --step \":ubuntu: Ubuntu 18.04 Build\""
      - "./scripts/parallel-test.bash"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu18_1-9-0-develop"
        mount-checkout: false
    timeout: 60

  - label: ":ubuntu: Ubuntu 18.04 NP Tests"
    command:
      - "git clone ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO} && cd eos && git checkout ${BUILDKITE_COMMIT} && buildkite-agent artifact download \"build.tar.gz\" . --step \":ubuntu: Ubuntu 18.04 Build\""
      - "./scripts/serial-test.bash"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu18_1-9-0-develop"
        mount-checkout: false
    timeout: 60

  - wait:
    continue_on_failure: true

  - command: |
        cd scripts/metrics
        node --max-old-space-size=4096 test-metrics.js
    label: ":bar_chart: Test Metrics"
    agents:
      queue: "automation-apps-builder-fleet"
    timeout: 10
    soft_fail: true

  - wait

  - label: ":centos: CentOS 7 Package Builder"
    command: |
        git clone ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO}
        cd eos
        git checkout ${BUILDKITE_COMMIT}
        buildkite-agent artifact download "build.tar.gz" . --step ":centos: CentOS 7 Build"
        tar -zxf build.tar.gz
        echo "+++ :microscope: Starting package build"
        sudo yum install -y rpm-build
        mkdir -p /home/cicd/rpmbuild/BUILD
        mkdir -p /home/cicd/rpmbuild/BUILDROOT
        mkdir -p /home/cicd/rpmbuild/RPMS
        mkdir -p /home/cicd/rpmbuild/SOURCES
        mkdir -p /home/cicd/rpmbuild/SPECS
        mkdir -p /home/cicd/rpmbuild/SRPMS
        cd /home/cicd/eos/build/packages
        bash generate_package.sh rpm
        buildkite-agent artifact upload *.rpm
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:centos7_1-9-0-develop"
        mount-checkout: false
    env:
      OS: "el7"
      PKGTYPE: "rpm"
    timeout: 60

  - command: | # Ubuntu 16.04 Package Builder
        git clone ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO}
        cd eos
        git checkout ${BUILDKITE_COMMIT}
        buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: Ubuntu 16.04 Build"
        tar -zxf build.tar.gz
        echo "+++ :microscope: Starting package build"
        cd /home/cicd/eos/build/packages
        bash generate_package.sh deb
        buildkite-agent artifact upload *.deb
    label: ":ubuntu: Ubuntu 16.04 Package Builder"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu16_1-9-0-develop"
        mount-checkout: false
    env:
      OS: "ubuntu-16.04"
      PKGTYPE: "deb"
    timeout: 60

  - command: | # Ubuntu 18.04 Package Builder
        echo "--- :arrow_down: Downloading build directory"
        git clone ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO}
        cd eos
        git checkout ${BUILDKITE_COMMIT}
        buildkite-agent artifact download "build.tar.gz" . --step ":ubuntu: Ubuntu 18.04 Build"
        tar -zxf build.tar.gz
        echo "+++ :microscope: Starting package build"
        cd /home/cicd/eos/build/packages
        bash generate_package.sh deb
        buildkite-agent artifact upload *.deb
    label: ":ubuntu: Ubuntu 18.04 Package Builder"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu18_1-9-0-develop"
        mount-checkout: false
    env:
      OS: "ubuntu-18.04"
      PKGTYPE: "deb"
    timeout: 60

  - label: ":darwin: Mojave Package Builder"
    command:
      - "git clone ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO} && cd eos && git checkout ${BUILDKITE_COMMIT} && buildkite-agent artifact download \"build.tar.gz\" . --step \":darwin: [Darwin] Mojave Build\" && tar -xzf build.tar.gz"
      - "cd eos/build/packages && bash generate_package.sh brew"
      - "cd eos && buildkite-agent artifact upload build/packages/*.tar.gz"
      - "cd eos && buildkite-agent artifact upload build/packages/*.rb"
    agents:
      - "queue=mac-anka-node-fleet"
    plugins:
      chef/anka#v0.5.0:
        no-volume: true
        inherit-environment-vars: true
        bash-interactive: true
        vm-name: $ANKA_MOJAVE_TEMPLATE
        vm-registry-tag: "${ANKA_TEMPLATE_TAG}::${MAC_TAG}"
        always-pull: true
        debug: true
        wait-network: true
    timeout: 120
  - wait

  - command: | # Brew Updater
        echo "--- :arrow_down: Downloading brew files"
        echo \"--- :arrow_down: Downloading Build Directory\" && buildkite-agent artifact download "build/packages/eosio.rb" . --step ":darwin: Mojave Package Builder"
    label: ":darwin: Brew Updater"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths:
      - "build/packages/eosio.rb"
    timeout: 5
  - command: | # Git Submodule Regression Check
        echo "+++ :microscope: Running git submodule regression check" && \
        ./scripts/submodule_check.sh
    label: "Git Submodule Regression Check"
    agents:
      queue: "automation-large-builder-fleet"
    timeout: 5

